= Glucose Measurement and Units
:icons: font
:stem: latexmath

Blood glucose is a measure of how much glucose is in your blood.
This is typically measured in mg/dL (milligrams per deciliter) and mmol/L (millimoles per liter).
The units you use for glucose measurements will vary depending on which country you live in.

[#_conversions]
== Conversions

Converting between mg/dL and mmol/L can be done by dividing or multiplying by a factor of stem:[18].

* To convert mg/dL -> mmol/L: divide the reading by stem:[18]
* To convert mmol/L -> mg/dL: multiply the reading by stem:[18]

++++
<details>
<summary>Click to see a conversion chart</summary>
++++

// antora does not use asciidoctor 2.0 yet, so the %collapsible block does not work. using a <details> tag to get around this limitation
//.Click to see a conversion chart
//[%collapsible]
//====

[%autowidth]
[cols="^1,^1"]
|===
|mg/dL -> mmol/L | mmol/L -> mg/dL

| 40 ~ 2.2 | 2.0 ~ 36
| 45 ~ 2.5 | 2.5 ~ 45
| 50 ~ 2.8 | 3.0 ~ 54
| 55 ~ 3.1 | 3.5 ~ 63
| 60 ~ 3.3 | 4.0 ~ 72
| 65 ~ 3.6 | 4.5 ~ 81
| 70 ~ 3.9 | 5.0 ~ 90
| 75 ~ 4.2 | 5.5 ~ 99
| 80 ~ 4.4 | 6.0 ~ 108
| 85 ~ 4.7 | 6.5 ~ 117
| 90 ~ 5.0 | 7.0 ~ 126
| 95 ~ 5.3 | 7.5 ~ 135
| 100 ~ 5.6 | 8.0 ~ 144
| 110 ~ 6.2 | 8.5 ~ 153
| 120 ~ 6.7 | 9.0 ~ 162
| 130 ~ 7.2 | 9.5 ~ 171
| 140 ~ 7.8 | 10.0 ~ 180
| 150 ~ 8.3 | 10.5 ~ 189
| 160 ~ 8.9 | 11.0 ~ 198
| 170 ~ 9.4 | 11.5 ~ 207
| 180 ~ 10.0 | 12.0 ~ 216
| 190 ~ 10.6 | 12.5 ~ 225
| 200 ~ 11.1 | 13.0 ~ 234
| 220 ~ 12.2 | 13.5 ~ 243
| 240 ~ 13.3 | 14.0 ~ 252
| 260 ~ 14.4 | 14.5 ~ 261
| 280 ~ 15.5 | 15.0 ~ 270
| 300 ~ 16.7 | 16.0 ~ 288
| 320 ~ 17.8 | 17.0 ~ 306
| 340 ~ 18.9 | 18.0 ~ 324
| 360 ~ 20.0 | 19.0 ~ 342
| 380 ~ 21.1 | 20.0 ~ 360
| 400 ~ 22.2 | 21.0 ~ 378
| 420 ~ 23.3 | 22.0 ~ 396
| 440 ~ 24.4 | 23.0 ~ 414
| 460 ~ 25.5 | 24.0 ~ 432
|===

//====
++++
</details>
++++

== Measurement units per country

A chart of blood glucose measurement units used per country can be found below.
Please note that the information on this chart may be out of date or inaccurate for some countries. +
_Do not rely on this chart for any medical decisions, it is only intended to give a better understanding of where certain measurement units may be used._

++++
<details>
<summary>Click to see a chart of the units</summary>
++++

//.Click to see a chart of the units
//[%collapsible]
//====

[%autowidth]
[cols="^1,^1"]
|===
| Country | Glucose Measurement Unit(s)

|Algeria|mg/dL
|Argentina|mg/dL
|Australia|mmol/L
|Austria|mg/dL
|Bahrain|mg/dL
|Bangladesh|mg/dL
|Belgium|mg/dL
|Brazil|mg/dL
|Canada|mmol/L
|Caribbean Countries|mg/dL
|Chile|mg/dL
|China|mmol/L
|Columbia|mg/dL
|Czech Republic|mmol/L
|Denmark|mmol/L
|Ecuador|mg/dL
|Egypt|mg/dL
|Finland|mmol/L
|France|mg/dL
|Georgia|mg/dL
|Germany|mg/dL, mmol/L
|Greece|mg/dL
|Hong Kong|mmol/L
|India|mg/dL
|Indonesia|mg/dL
|Ireland|mmol/L
|Israel|mg/dL
|Italy|mg/dL
|Japan|mg/dL
|Jordan|mg/dL
|Kazakhstan|mmol/L
|Korea|mg/dL
|Kuwait|mg/dL
|Lebanon|mg/dL
|Luxembourg|mg/dL
|Malaysia|mmol/L
|Malta|mmol/L
|Mexico|mg/dL
|Netherlands|mmol/L
|New Zealand|mmol/L
|Norway|mmol/L
|Oman|mg/dL
|Peru|mg/dL
|Philippines|mg/dL
|Poland|mg/dL
|Portugal|mg/dL
|Qatar|mg/dL
|Russia|mmol/L
|Saudi Arabia|mg/dL
|Singapore|mmol/L
|Slovakia|mmol/L
|Slovenia|mmol/L
|South Africa|mmol/L
|Spain|mg/dL
|Sub-Saharan Africa|mg/dL, mmol/L
|Sweden|mmol/L
|Switzerland|mmol/L
|Syria|mg/dL
|Taiwan|mg/dL
|Thailand|mg/dL
|Tunisia|mg/dL
|Turkey|mg/dL
|Ukraine|mmol/L
|United Arab Emirates (UAE)|mg/dL
|United Kingdom|mmol/L
|United States|mg/dL
|Uruguay|mg/dL
|Venezuela|mg/dL
|Vietnam|mmol/L
|Yemen|mg/dL
|===

__from https://web.archive.org/web/20110706100159/http://www.abbottdiabetescare.com.au/diabetes-faq-measure-units.php[Diabetes FAQs - Blood Glucose Measurement Units - Abbott Diabetes Care]__

//====
++++
</details>
++++

== Exact Conversions

IMPORTANT: This is cool, extra info if you want to know the intricate details of the glucose unit conversion factor. *_This will not affect your diabetes management at all, so it is entirely educational._*

The conversion factor of stem:[18] given in the <<_conversions,conversions section above>> is not as precise as it can be.
This preciseness was traded for ease of understanding as it's not necessary for the average person to use the exact conversion factor in everyday glucose conversions.

=== Why don't we use the precise conversion factor for most calculations?

The percentage difference between the simplified factor (stem:[18]) and the exact/precise factor (stem:[18.0156]) is stem:[0.0866291\%], which is an extremely negligible loss in precision.
In most cases, someone who needs to convert a blood glucose value will not be dealing with such a large value that the precision loss with the simplified factor would be critical.
As the blood glucose value you're converting from increases, the difference between the simplified and precise factors increases linearly.

You can use https://www.desmos.com/calculator/7ct6n1ufwq[this Desmos calculator] to see for yourself.
It's difficult to see the actual difference on your screen, but if you click and drag on the line you can see the Y value (difference between the two conversion factors) increasing slowly with the X value (blood glucose in mg/dL).

=== What circumstances would you use the precise conversion factor in?

The main usage for the precise conversion factor would be in calculators.
As stated in the previous answer, most people will not be dealing with large glucose values that results in a noticeable drift between the simplified and precise factors (as the value gets larger, so does the difference between the simplified and exact factors), but calculators may encounter these large values that can make a noticeable difference in the resulting value.
In addition, the calculator may need to perform further calculations using the result (for example, estimating the xref:diabetes:measurement:a1c/a1c.adoc[HbA1c]) which means having the result as precise as possible will help ensure calculations are as accurate as they can be.

=== More information

If you would like to see an explanation of how this exact conversion factor is found, continue to xref:diabetes:measurement:glucose/glucose-unit-conversion-explanation.adoc[the next page].
