name: Inform Antora repo on push
on: push

jobs:
  build:
    name: Dispatch to Antora repo
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: p5nbtgip0r.github.io
          owner: p5nbTgip0r
          event_type: build_publish